### ISSUE TITLE
either-5.0.1.1 tarball has executable text files

### ISSUE THREAD

**Issue by juhp** [ekmett/either#63] opened 2019-12-12 05:11 UTC
`either-5.0.1.1.tar.gz` contains executable doc files:

```
 -rwxr-xr-x       0/0            85 Sep  9 09:46 2001 either-5.0.1.1/.ghci
 -rwxr-xr-x       0/0           280 Sep  9 09:46 2001 either-5.0.1.1/.gitignore
 -rwxr-xr-x       0/0          8746 Sep  9 09:46 2001 either-5.0.1.1/.travis.yml
 -rwxr-xr-x       0/0           767 Sep  9 09:46 2001 either-5.0.1.1/.vim.custom
 -rwxr-xr-x       0/0          2986 Sep  9 09:46 2001 either-5.0.1.1/CHANGELOG.markdown
 -rwxr-xr-x       0/0           432 Sep  9 09:46 2001 either-5.0.1.1/README.markdown
```

This doesn't seem to be the case for either-5.0.1.
I reporting in the context of us adding either to Fedora, thanks.

**Comment by RyanGlScott** [comment] 2019-12-12 11:17
Are you entirely certain that this isn't a change that Hackage itself is making to uploaded packages? I just checked out a fresh copy of the `either` GitHub repo and none of those files have executable permissions:

```
$ git clone git@github.com:ekmett/either
$ cd either/
$ ls -alh
total 76K
-rw-rw-r--  1 rgscott rgscott 3.0K Dec 12 06:12 CHANGELOG.markdown
-rw-rw-r--  1 rgscott rgscott   85 Dec 12 06:12 .ghci
-rw-rw-r--  1 rgscott rgscott  280 Dec 12 06:12 .gitignore
-rw-rw-r--  1 rgscott rgscott  432 Dec 12 06:12 README.markdown
-rw-rw-r--  1 rgscott rgscott 8.8K Dec 12 06:12 .travis.yml
-rw-rw-r--  1 rgscott rgscott  767 Dec 12 06:12 .vim.custom
```

Furthermore, there's nothing in the [commits between v5.0.1 and v5.0.1.1](https://github.com/ekmett/either/compare/v5.0.1...v5.0.1.1) to indicate that the permissions changed on `either`'s side.

**Comment by RyanGlScott** [comment] 2019-12-12 11:24
Actually, I'm unable to reproduce the behavior you originally reported:

```
$ cabal get either-5.0.1.1 && cd either-5.0.1.1/
Unpacking to either-5.0.1.1/
rgscott at gearloose in ~/.../Hacking/Haskell/either-5.0.1.1
$ ls -alh
total 60K
-rw-rw-r--  1 rgscott rgscott 3.0K Sep  8  2001 CHANGELOG.markdown
-rw-rw-r--  1 rgscott rgscott   85 Sep  8  2001 .ghci
-rw-rw-r--  1 rgscott rgscott  280 Sep  8  2001 .gitignore
-rw-rw-r--  1 rgscott rgscott  432 Sep  8  2001 README.markdown
-rw-rw-r--  1 rgscott rgscott 8.6K Sep  8  2001 .travis.yml
-rw-rw-r--  1 rgscott rgscott  767 Sep  8  2001 .vim.custom
```

Where are you getting `either-5.0.1.1.tar.gz` from?

**Comment by RyanGlScott** [comment] 2019-12-12 11:59
Never mind, I see what is happening here.

First, ignore https://github.com/ekmett/either/issues/63#issuecomment-564967183. I was obtaining the tarball through `cabal get`, which apparently gives different permissions than if you download the tarball directly from http://hackage.haskell.org/package/either-5.0.1.1/either-5.0.1.1.tar.gz. I can reproduce the behavior you're seeing by downloading the latter tarball:

```
$ wget http://hackage.haskell.org/package/either-5.0.1.1/either-5.0.1.1.tar.gz
$ tar -xvf either-5.0.1.1.tar.gz 
$ cd either-5.0.1.1/
$ ls -alh
total 60K
-rwxr-xr-x 1 ryanglscott ryanglscott 3.0K Sep  8  2001 CHANGELOG.markdown
-rwxr-xr-x 1 ryanglscott ryanglscott   85 Sep  8  2001 .ghci
-rwxr-xr-x 1 ryanglscott ryanglscott  280 Sep  8  2001 .gitignore
-rwxr-xr-x 1 ryanglscott ryanglscott  432 Sep  8  2001 README.markdown
-rwxr-xr-x 1 ryanglscott ryanglscott 8.6K Sep  8  2001 .travis.yml
-rwxr-xr-x 1 ryanglscott ryanglscott  767 Sep  8  2001 .vim.custom
```

The next question is: why did those files get executable permissions added? I originally speculated this to be a Hackage quirk, but it turns out that this is instead a quirk of `cabal v2-sdist`. I had bundled `either-5.0.1` using `v1-sdist` and `either-5.0.1.1` using `v2-sdist`, which is why the executable permissions only showed up in the latter.

Someone has already filed a bug report about this at haskell/cabal#5813. Given that this is a `cabal` issue, not an `either` issue, I'm going to close this in favor of haskell/cabal#5813.

**Closed by RyanGlScott** 2019-12-12 11:59 UTC
Labels: info needed

**Comment by juhp** [comment] 2019-12-12 14:16
Thanks for tracking this down, Ryan!  I had no idea.
